### ISSUE TITLE
Get version information

### ISSUE THREAD

**Issue by IonicaBizau** [sindresorhus/npm-keyword#1]
It seems that [`el` doesn't contain version related information](https://github.com/sindresorhus/npm-keyword/blob/6fbe493b3bad3d742f0f88dc15325c8c9b447b66/index.js#L19-L22).

Is it possible to get the latest module versions?

**Comment by kevva** [comment]
Use https://github.com/sindresorhus/package-json to get the version.

**Comment by sindresorhus** [comment]
@othiym23 Is there any way to get more data in this [API request](https://github.com/sindresorhus/npm-keyword/blob/6fbe493b3bad3d742f0f88dc15325c8c9b447b66/index.js#L29)?

**Comment by IonicaBizau** [comment]
@kevva Always liked these tiny modules. :smile: Thanks! :+1:

**Comment by othiym23** [comment]
@sindresorhus No, and in fact the plan is to start reducing the functionality exposed via the `npm-registry-couchapp` design docs, because they're slow and inflexible. We have the beginnings of a replacement API for this at `api.npmjs.org`, but right now that's just the download counts API, and there's not a really good way for non-npm consumers of this kind of metadata to make requests for API endpoints.

Therefore, I'm tagging in @seldo, because this is a decision that should be made at the CTO level: how do we want to file user requests for new API endpoints like this? This won't be the last time this comes up.

**Comment by seldo** [comment]
Nearly everything one could want to do with the registry's API is a subset of what we ourselves do in the website, which is served by an internal api called "registry relational". This is a significantly more flexible and maintainable service that we have been rapidly extending.

It is already a long-term plan of ours to expose this API to the public, but that means wrapping it in higher levels of security, choosing an authentication mechanism of some kind (at present it relies on internal auth), and hardening it with DDOS and rate-limiting. This stuff is nontrivial and, given our gigantic wish list of cool features and small team, it means it falls pretty far along the road map right now.

In the meantime, let's collect feature requests at this freshly-minted repo:
https://github.com/npm/public-api/issues

This will give us a central place to track these and also gauge the level of demand.

**Comment by zeke** [comment]
:+1:

**Comment by IonicaBizau** [comment]
Sounds cool! :+1:
